### ISSUE TITLE
付费插件有些显示不了配置模板，望解决

### ISSUE THREAD

**Issue by mohan2096** [sit17/btpanel_crack#1]
![TIM截图20190401013340](https://user-images.githubusercontent.com/5841396/55292507-51d24e80-541e-11e9-9b68-9c41fb6dc063.png)

**Comment by sit17** [comment]
下载完插件不要直接运行,通过文件夹清理掉so文件和pyc文件,然后复制对应插件文件夹的内容,最后重启宝塔面板服务(不是重启服务器).
